development:
  adapter: postgresql
  database: 'forthlight_dev'
  username: 'lightbringer'
  password: 'global_dev'
  host: 88.80.189.110
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: 'forthlight_dev'
  username: 'lightbringer'
  password: 'local_dev'
  host: localhost
  pool: 5
  timeout: 5000

staging:
  adapter: postgresql
  database: 'forthlight_dev'
  username: 'lightbringer'
  password: 'global_dev'
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: 'forthlight_dev'
  username: 'lightbringer'
  password: 'global_dev'
  host: localhost
  pool: 5
  timeout: 5000
